function [gameOver] = checkForWin(currentBoard, chip1, chip2)
%checkForWin checks the board to see if the game has been won
% currentBoard: The current board variable (with sprite numbers)
% chip1: Sprite number for player 1's chip 
% chip2: Sprite number for player 2's chip
% gameOver: True if the game is over, False if no connect-4s are detected

gameOver = false;

% Horizontal Check -
for Row = 2:7
    for Column = 1:4
        if chip1 == currentBoard(Row, Column) && ...
                chip1 == currentBoard(Row, Column+1) && ...
                chip1 == currentBoard(Row, Column+2) && ...
                chip1 == currentBoard(Row, Column+3) || ...
                chip2 == currentBoard(Row, Column) && ...
                chip2 == currentBoard(Row, Column+1) && ...
                chip2 == currentBoard(Row, Column+2) && ...
                chip2 == currentBoard(Row, Column+3) 
            gameOver = true;
            return
        end
    end
end


% Vertical Check |
for Row = 2:4
    for Column = 1:7
        if chip1 == currentBoard(Row, Column) && ...
             chip1 == currentBoard(Row+1, Column) && ...
             chip1 == currentBoard(Row+2, Column) && ...
             chip1 == currentBoard(Row+3, Column) || ...
             chip2 == currentBoard(Row, Column) && ...
             chip2 == currentBoard(Row+1, Column) && ...
             chip2 == currentBoard(Row+2, Column) && ...
             chip2 == currentBoard(Row+3, Column)  ...
            
            gameOver = true;
            return
        end
    end
end

% Diagonal Check /
for Row = 7:-1:4
    for Column = 1:4
        if chip1 == currentBoard(Row, Column) && ...
             chip1 == currentBoard(Row-1, Column+1) && ...
             chip1 == currentBoard(Row-2, Column+2) && ...
             chip1 == currentBoard(Row-3, Column+3) || ...
             chip2 == currentBoard(Row, Column) && ...
             chip2 == currentBoard(Row-1, Column+1) && ...
             chip2 == currentBoard(Row-2, Column+2) && ...
             chip2 == currentBoard(Row-3, Column+3)  ...
            
            gameOver = true;
            return
        end
    end
end

% Diagonal Check \
for Row = 2:4
    for Column = 1:4
        if chip1 == currentBoard(Row, Column) && ...
             chip1 == currentBoard(Row+1, Column+1) && ...
             chip1 == currentBoard(Row+2, Column+2) && ...
             chip1 == currentBoard(Row+3, Column+3) || ...
             chip2 == currentBoard(Row, Column) && ...
             chip2 == currentBoard(Row+1, Column+1) && ...
             chip2 == currentBoard(Row+2, Column+2) && ...
             chip2 == currentBoard(Row+3, Column+3)  ...
            
            gameOver = true;
            return
        end
    end
end

end